### ISSUE TITLE
nn criterions don't compute the gradient

### ISSUE THREAD

**Issue by wondervictor** [wondervictor/DeepQLearning#1]
```
    "nn criterions don't compute the gradient w.r.t. targets - please " \
AssertionError: nn criterions don't compute the gradient w.r.t. targets - please mark these variables as volatile or not requiring gradients
```

**Comment by crazylyf** [comment]
@wondervictor  Is this confirmed as a bug?

**Comment by wondervictor** [comment]
Yeah, I need to check the properties of variables and the network.

**Comment by wondervictor** [comment]
Now the bug has been fixed :)
I used the wrong loss function (CrossEntropy)

**Comment by crazylyf** [comment]
Great, thanks~

**Comment by dss74ds30** [comment]
hello? I have met with the same problem and I also used the cross entropy, could you please tell me what's wrong with it and how to fix it?

**Comment by wondervictor** [comment]
check the formats of your `inputs` and `target`
example: 4 classes batch size =  2

````python
inputs = [[0,0.2,0.5,0.3],[0.4,0.3,0.1,0]]
target = [2,4]
````

* `inputs`: `size=[N,C]`
* `targets`: `size=[N]`

**Comment by dss74ds30** [comment]
Thank you!

I've fixed that problem!


Write


Sent from Outlook<http://aka.ms/weboutlook>
________________________________
